config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'
  resources :microposts
  resources :users
  resources :sessions
  resources :microposts do
    resources :comments
    delete :delete_attachment
  end
  get "/auth/google_oauth2/callback", to: "sessions#create"
  get "/login", to: redirect("/auth/google_oauth2")
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'users#new'
  
  post '/microposts/:id/vote' => "microposts#vote", as: :vote
  post '/microposts/:id/watch' => "microposts#watch", as: :watch
  put '/microposts/:id/status' => "microposts#update_status", as: :update_status
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  belongs_to :assignee, class_name: 'User', foreign_key: :assignee_id, optional: true
  has_many :comments, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :watchers, dependent: :destroy
  has_many_attached :things, dependent: :destroy
  
  def self.status
    ["New", "Open", "On hold", "Resolved", "Duplicate", "Invalid", "Won't fix", "Closed"]
  end
  def self.type
      ["Bug", "Enhancement", "Proposal", "Task"]
  end
  def self.priority
      ["Trivial", "Minor", "Major", "Critical", "Blocker"]
  end
    #validates :user_id, presence: true
    
  
  default_scope { order(created_at: :desc) }
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :set_micropost, only: [:show, :edit, :update, :destroy]
  before_action :authenticate
  protect_from_forgery
  
  # GET /microposts
  # GET /microposts.json
  def index
    respond_to do |format|
      @microposts = Micropost.all
      
      if params.has_key?(:assignee)
          if User.exists?(id: params[:assignee])
            @microposts = @microposts.where(assignee_id: params[:assignee])
          else
            format.json {render json: {"error":"User with id="+params[:assignee]+" does not exist"}, status: :unprocessable_entity}
          end
      end
      
      if params.has_key?(:type_issue)
          @microposts = @microposts.where(type_issue: params[:type_issue])
      end
      
      if params.has_key?(:priority)
          @microposts = @microposts.where(priority: params[:priority])
      end
      
      if params.has_key?(:status)
          if params[:status] == "New&Open"
            @microposts = @microposts.where(status: ["Open","New"])
          else
            @microposts = @microposts.where(status: params[:status])
          end
      end
      
      if params.has_key?(:watcher)
          if User.exists?(id: params[:watcher])
            @microposts = Micropost.includes(:watchers).where(watchers:{user_id: params[:watcher]})
          else
            format.json {render json: {"error":"User with id="+params[:watcher]+" does not exist"}, status: :unprocessable_entity}
          end
      end
      
      format.html
      format.json {render json: @microposts}
    end
  end

  # GET /microposts/1
  # GET /microposts/1.json
  def show
    respond_to do |format|
      format.html
      format.json {render json: @micropost}
    end
  end

  # GET /microposts/new
  def new
    @micropost = Micropost.new
  end

  # GET /microposts/1/edit
  def edit
  end

  # POST /microposts
  # POST /microposts.json
  def create
    @micropost = Micropost.new(micropost_params)
    if (logged_in?)
      @micropost.user_id = current_user.id
      @micropost.assignee_id = current_user.id
    end
    respond_to do |format|
      if @micropost.save
        @watcher = Watcher.new
        if (logged_in?)
          @watcher.user_id = current_user.id
        else
          @watcher.user_id = @micropost.user_id
        end
        @watcher.micropost_id = @micropost.id
        @watcher.save
        @micropost.increment!("Watchers")
        format.html { redirect_to @micropost, notice: 'Micropost was successfully created.' }
        #format.json { render :show, status: :created, location: @micropost }
        format.json { render json: @micropost, status: :created}
      else
        format.html { render :new }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /microposts/1
  # PATCH/PUT /microposts/1.json
  def update
    respond_to do |format|
      if micropost_params.has_key?(:body)
        if (!micropost_params[:body].empty?)
          @comment = Comment.new
          @comment.body = micropost_params[:body]
          @comment.micropost_id = @micropost.id
          @comment.user_id = current_user.id
          @comment.save
        end
      end
      if @micropost.update(micropost_params.except(:body))
        format.html { redirect_to @micropost, notice: 'Micropost was successfully updated.' }
        format.json { render :show, status: :ok, location: @micropost }
      else
        format.html { render :edit }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def vote
    respond_to do |format|
      @issue_to_vote = Micropost.find(params[:id])
      if (logged_in?)
        if !Vote.exists?(:micropost_id => @issue_to_vote.id, :user_id => current_user.id)
          @vote = Vote.new
          @vote.user_id = current_user.id
          @vote.micropost_id = @issue_to_vote.id
          @vote.save
          @issue_to_vote.increment!(:Votes)
        else
          @vote = Vote.where(micropost_id: params[:id], user_id: current_user.id).take
          @vote.destroy
          @issue_to_vote.decrement!(:Votes)
        end
        format.html {redirect_to request.referrer}
        format.json { render json: @issue_to_vote, status: :ok }
      else
        if !Vote.exists?(:micropost_id => @issue_to_vote.id, :user_id => params[:user_id])
          @vote = Vote.new
          @vote.user_id = params[:user_id]
          @vote.micropost_id = @issue_to_vote.id
          @vote.save
          @issue_to_vote.increment!(:Votes)
        else
          @vote = Vote.where(micropost_id: params[:id], user_id: params[:user_id]).take
          @vote.destroy
          @issue_to_vote.decrement!(:Votes)
        end
        format.html {redirect_to request.referrer}
        format.json { render json: @issue_to_vote, status: :ok }
      end
    end
  end
  
  def watch
    respond_to do |format|
      @issue_to_watch = Micropost.find(params[:id])
      if (logged_in?)
        if !Watcher.exists?(:micropost_id => @issue_to_watch.id, :user_id => current_user.id)
          @watcher = Watcher.new
          @watcher.user_id = current_user.id
          @watcher.micropost_id = @issue_to_watch.id
          @watcher.save
          @issue_to_watch.increment!("Watchers")
        else
          @watcher = Watcher.where(micropost_id: params[:id], user_id: current_user.id).take
          @watcher.destroy
          @issue_to_watch.decrement!("Watchers")
        end
        format.html {redirect_to request.referrer}
        format.json { render json: @issue_to_watch, status: :ok }
      else 
        if !Watcher.exists?(:micropost_id => @issue_to_watch.id, :user_id => params[:user_id])
          @watcher = Watcher.new
          @watcher.user_id = params[:user_id]
          @watcher.micropost_id = @issue_to_watch.id
          @watcher.save
          @issue_to_watch.increment!("Watchers")
        else
          @watcher = Watcher.where(micropost_id: params[:id], user_id: params[:user_id]).take
          @watcher.destroy
          @issue_to_watch.decrement!("Watchers")
        end
        format.html {redirect_to request.referrer}
        format.json { render json: @issue_to_watch, status: :ok }
      end
    end
  end
  
  def update_status
    respond_to do |format|
      @issue_to_update = Micropost.find(params[:id])
      @issue_to_update.update_attribute("status", params[:status])
      
      format.html { redirect_to @issue_to_update }
      format.json { render json: @issue_to_update, status: :ok }
    end
  end
  
  def delete_attachment
    @attach_obj = ActiveStorage::Attachment.find(params[:micropost_id])
    @attach_obj.purge
    redirect_back(fallback_location: request.referer)
  end

  # DELETE /microposts/1
  # DELETE /microposts/1.json
  def destroy
    @issue = Micropost.find(params[:id])
    @issue.destroy
    respond_to do |format|
      format.html { redirect_to issues_url, notice: 'The issue was successfully destroyed.' }
      format.json { render json: {"message": "success"}, status: :ok }
    end
  end
  
  def authenticate
    if(!logged_in?)
      api_key = request.headers['X-Api-Key']
      @user = User.where(api_key: api_key).first if api_key
      unless @user
          head :unauthorized
        return false
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_micropost
      @micropost = Micropost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def micropost_params
      params.permit(:user_id, :title, :description, :type_issue, :priority, :assignee_id, :body, things: [])
    end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
  
end

app/views/microposts/_comment_form.html.erb
<%= form_with(model: [ @micropost, @micropost.comments.build ], local: true) do |form| %>
     <p>
       <div class="input" style="margin-left: -145px">
          <%= form.text_area :body, :placeholder => "What do you want to say?"%>
       </div>
     </p>
     
    <div class="actions">
      <%= form.submit :"Save", :class => 'save' %>
      <%= link_to 'Cancel', micropost_url(@micropost), :class => 'cancel'%>
    </div>

<% end %>

app/views/microposts/_create_form.html.erb
<%= form_with(model: micropost, local: true) do |form| %>
  <% if micropost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(micropost.errors.count, "error") %> prohibited this micropost from being saved:</h2>

      <ul>
        <% micropost.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-group" style="margin: 50px 0 20px 39px"> 
    Title* <%= form.text_field :title, :class => 'title', :required => true %>
  </div>
  
  <div class="input-group" style="margin-bottom: 20px" >
    Description <%= form.text_area :description %>
  </div>
  
  <div class="input-group" style="margin: 0 0 20px 36px">
    Kind* <%= form.select :type_issue, options_for_select([ "bug", "enhancement", "proposal", "task" ], "bug") %>
  </div>
  
    <div class="input-group" style="margin: 0 0 20px 18px">
    Priority* <%= form.select :priority, options_for_select([ "major", "minor", "trivial", "critical", "blocker"], "major") %>
  </div>
  
  <div class="input" style="margin: 0 0 50px -12px">
    Attachments <%= form.file_field :things, multiple: true %>
  </div>


  <div class="actions" style="margin-left: 1150px">
    <%= form.submit :"Create Issue", :class => 'submit'%>
    <%= link_to 'Cancel', microposts_path, :class => 'cancel' %>
  </div>
  
<% end %>

app/views/microposts/_edit_form.html.erb
<%= form_with(model: micropost, local: true) do |form| %>
  <% if micropost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(micropost.errors.count, "error") %> prohibited this micropost from being saved:</h2>

      <ul>
        <% micropost.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-group" style="margin: 40px 0 20px 39px"> 
    Title* <%= form.text_field :title, :class => 'title', :required => true %>
  </div>

  <div class="input-group" style="margin-bottom: 20px" >
    Description <%= form.text_area :description %>
  </div>
  
  <div class="reporter" style="margin: 0 0 20px 15px">
    Reporter
    <% options = options_from_collection_for_select(User.all, 'id', 'name')%>
    <%= form.select :assignee_id, options, {:include_blank => 'No assigned user'}%>
  </div>
  
  <div class="input-group" style="margin: 0 0 20px 36px">
    Kind* <%= form.select :type_issue, options_for_select([ "bug", "enhancement", "proposal", "task" ], "bug") %>
  </div>
  
    <div class="input-group" style="margin: 0 0 20px 18px">
    Priority* <%= form.select :priority, options_for_select([ "major", "minor", "trivial", "critical", "blocker"], "major") %>
  </div>
  
  <div class="input" style="margin: 0 0 20px -12px">
    Attachments <%= form.file_field :things, multiple: true %>
  </div>
  
  <div class="input-group" style="margin-bottom: 50px" >
    Comment <%= form.text_area :body %>
  </div>


  <div class="actions" style="margin-left: 1150px">
    <%= form.submit :"Update Issue", :class => 'submit'%>
    <%= link_to 'Cancel', microposts_path, :class => 'cancel' %>
  </div>
  
<% end %>

app/views/microposts/_form.html.erb
<%= form_with(model: micropost, local: true) do |form| %>
  <% if micropost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(micropost.errors.count, "error") %> prohibited this micropost from being saved:</h2>

      <ul>
        <% micropost.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-group" style="margin: 50px 0 20px 39px"> 
    Title* <%= form.text_field :title, :class => 'title', :required => true %>
  </div>
  
  <div class="input-group" style="margin-bottom: 20px" >
    Description <%= form.text_area :description %>
  </div>
  
  <div class="input-group" style="margin: 0 0 20px 36px">
    Kind* <%= form.select :type, options_for_select([ "bug", "enhancement", "proposal", "task" ], "bug") %>
  </div>
  
    <div class="input-group" style="margin: 0 0 20px 18px">
    Priority* <%= form.select :priority, options_for_select([ "major", "minor", "trivial", "critical", "blocker"], "major") %>
  </div>
  
  <div class="input" style="margin: 0 0 50px -12px">
    Attachments <input type="file" multiple="multiple">
  </div>


  <div class="actions" style="margin-left: 1150px">
    <%= form.submit :"Create Issue", :class => 'submit'%>
    <%= link_to 'Cancel', microposts_path, :class => 'cancel' %>
  </div>
  
<% end %>

app/views/microposts/edit.html.erb
<h2>Issues</h2>
<h4>Edit issue</h4>


<%= render 'edit_form', micropost: @micropost %>

app/views/microposts/index.html.erb
<!DOCTYPE html>
<html>
<head>
<style>
  td:hover {
    background-color:#f5f5f5;
    
  }
  table{
    border-collapse: collapse;
    width: 100%;
  }
  table thead tr th{
      border-bottom: 1px solid lightgray;
      text-align: left;
  }
  table th, table td{ /* Added padding for better layout after collapsing */
      padding: 4px 8px;
  }
</style>
</head>

<body>
  <p id="notice"><%= notice %></p>
  
  <div style="position: relative;" class="header">
    <h1>Issues</h1>
    <div style="position: absolute; top: 0; right: 0;">
      <% if current_user != nil %>
        <%= link_to 'Create issue', new_micropost_path %>
      <% end %>
       <input type="text" id="myInput" onkeyup="search()" placeholder="Find issues">
    </div>
  </div>
  
  <div style = "display: inline; position: relative;">
    <a>Filter by: </a>
    <a href="/microposts">All</a>
    <a><%= link_to "Open", microposts_url(status: "New&Open")%></a>
    <% if current_user != nil %>
      <a><%= link_to "My issues", microposts_url(assignee: current_user.id)%></a>
      <a><%= link_to "Watching", microposts_url(watcher: current_user.id)%></a>
    <% else %>
      <a>My Issues</a>
      <a>Watching</a>
    <% end %>
  </div>

  <table id = "myTable">
    <col width="48%">
    <col width="5%">
    <col width="5%">
    <col width="8%">
    <col width="8%">
    <col width="8%">
    <col width="8%">
    <col width="8%">
    <col width="2%">
    <thead >
      <tr>
        <th onclick="sortTable(0)">Title</th>
        <th onclick="sortTable(1)">T</th>
        <th onclick="sortTable(2)">P</th>
        <th onclick="sortTable(3)">Status</th>
        <th onclick="sortTable(4)">Votes</th>
        <th onclick="sortTable(5)">Assignee</th>
        <th onclick="sortTable(6)"> Created</th>
        <th onclick="sortTable(7)">Updated</th>
        <th colspan="1"></th>
      </tr>
    </thead>
  
  
    <tbody>
      <% @microposts.each do |micropost| %>
        <tr>
          <td><%= link_to micropost.title, micropost, class:"btn-link" %></td>
          <td><%= link_to micropost.type_issue , microposts_url(type_issue: micropost.type_issue), class:"btn-link" %></td>
          <td><%= link_to micropost.priority , microposts_url(priority: micropost.priority), class:"btn-link" %></td>
          <td><%= link_to micropost.status, microposts_url(status: micropost.status), class:"btn-link" %></td>
          <td><%= micropost.Votes %></td>
          <% if !micropost.assignee.nil? %>
            <td><%= link_to micropost.assignee.name, microposts_url(assignee: micropost.assignee.id), class:"btn-link" %></td>
          <% else %>
            <td></td>
          <% end %>
          <td><%= time_ago_in_words(micropost.created_at) + " ago" %></td>
          <td><%= time_ago_in_words(micropost.updated_at) + " ago" %></td>
          <% if current_user != nil %>
            <% if !Watcher.exists?(:micropost_id => micropost.id, :user_id => current_user.id) %>
              <td><%= link_to 'Watch', watch_url(id: micropost.id, view: "micropost"), method: :post, class: "vote" %></td>
            <% else %>
              <td><%= link_to 'Unwatch', watch_url(id: micropost.id, view: "micropost"), method: :post, class: "vote" %></td>
            <% end %>
          <% end %>
          
          <% if false %>
            <td><%= link_to 'Show', micropost %></td>
            <td><%= link_to 'Edit', edit_micropost_path(micropost) %></td>
            <td><%= link_to 'Delete', micropost, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
  
  <script type='text/javascript'>
    function search() {
      var input, filter, table, tr, td, i, txtValue;
      input = document.getElementById("myInput");
      filter = input.value.toUpperCase();
      table = document.getElementById("myTable");
      tr = table.getElementsByTagName("tr");
      for (i = 0; i < tr.length; i++) {
        td = tr[i].getElementsByTagName("td")[0];
        if (td) {
          txtValue = td.textContent || td.innerText;
          if (txtValue.toUpperCase().indexOf(filter) > -1) {
            tr[i].style.display = "";
          } else {
            tr[i].style.display = "none";
          }
        }       
      }
    }
    
    function sortTable(column) {
      var table, rows, switching, i, x, y, shouldSwitch;
      table = document.getElementById("myTable");
      switching = true;
      /* Make a loop that will continue until
      no switching has been done: */
      while (switching) {
        // Start by saying: no switching is done:
        switching = false;
        rows = table.rows;
        /* Loop through all table rows (except the
        first, which contains table headers): */
        for (i = 1; i < (rows.length - 1); i++) {
          // Start by saying there should be no switching:
          shouldSwitch = false;
          /* Get the two elements you want to compare,
          one from current row and one from the next: */
          x = rows[i].getElementsByTagName("TD")[column];
          y = rows[i + 1].getElementsByTagName("TD")[column];
          // Check if the two rows should switch place:
          if (x.innerHTML.toLowerCase() > y.innerHTML.toLowerCase()) {
            // If so, mark as a switch and break the loop:
            shouldSwitch = true;
            break;
          }
        }
        if (shouldSwitch) {
          /* If a switch has been marked, make the switch
          and mark that a switch has been done: */
          rows[i].parentNode.insertBefore(rows[i + 1], rows[i]);
          switching = true;
        }
      }
    }
    
    
  </script>
</body>

app/views/microposts/new.html.erb
<h2>Issues</h2>
<h4>Create issue</h4>

<%= render 'create_form', micropost: @micropost %>

app/views/microposts/show.html.erb
<p id="notice"><%= notice %></p>
<%= stylesheet_link_tag "dropdown_button" %>

<% if logged_in? %>
  <div class="btn_edit", style="float:right; padding-top:5px">
      <%= link_to 'Create issue', new_micropost_path %>
  </div>
<% end %>

<p>
  <h2><%= @micropost.title %></h2>
</p>

<p>
      Issue #<%= @micropost.id %>
</p>

<div style="float:right;">
  <% if logged_in? %>
    <% if current_user.id == @micropost.user_id %>
      <div class="dropdown">
        <div id="Content" class="btn_content", style="float: left">
          <% if @micropost.status == "Open" || @micropost.status == "New" %>
             <%= link_to 'Resolve', update_status_url(id: @micropost.id, status: "Resolved"), method: :put %>
          <% else %>
            <%= link_to 'Open', update_status_url(id: @micropost.id, status: "Open"), method: :put, class:'open'%>
          <% end %>
        </div>
        <%= javascript_include_tag "dropdown_show" %>
        <button onclick="myFunction()" class="dropbtn" >Workflow</button>
        <div id="myDropdown" class="dropdown-content">
          <% Micropost.status.each do |status| %>
            <% if status != @micropost.status %>
              <%= link_to(status, update_status_url(id: @micropost.id, status: status), method: :put) %>
              <% end %>
          <% end %>
       </div>
       <div class="btn_edit", style="float: right">
        <%= link_to 'Edit', edit_micropost_path(@micropost) %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

<p>
  <strong><%= @micropost.user.name %></strong>
  created an issue
  <time><%= @micropost.created_at.strftime('%Y-%m-%d')%></time>
</p>


<% if !(@micropost.description == "") %>
  <p class="description"><%= @micropost.description %></p>
<% else %>
  <p class="no-description">No description provided.</p>
<% end %>


<div style="padding: 8px; border: 1px solid #EAEAEA; float:right; padding-left: 25px;">
  <p style="padding-right: 10px;">
    <strong>Assignee</strong>
    <% if !@micropost.assignee.nil? %>
      <%= link_to  @micropost.assignee.name, microposts_url(assignee: @micropost.assignee.id), class:"btn-link" %> 
    <% else %>
      -
    <% end %>
  </p>  
    <p>
      <strong>Type</strong>
      <%= link_to @micropost.type_issue , microposts_url(type_issue: @micropost.type_issue) %>
    </p>
    <p>
      <strong>Priority</strong>
      <td><%= link_to@micropost.priority , microposts_url(priority: @micropost.priority) %></td>
    </p>

    <p>
      <strong>Status</strong>
      <%= link_to @micropost.status, microposts_url(status: @micropost.status)%>
    </p>

    <p>
      <strong>Votes</strong>
      <%= @micropost.Votes %>
      <% if current_user != nil %>
        <% if !Vote.exists?(:micropost_id => @micropost.id, :user_id => current_user.id) %>
          <%= link_to 'Vote for this issue', vote_url(id: @micropost.id), method: :post, class:"vote" %>
        <% else %>
          <%= link_to 'Remove vote', vote_url(id: @micropost.id), method: :post, class:"vote" %>
        <% end %>
      <% end %>
    </p>
    <p style="padding-right: 10px;">
      <strong>Watchers</strong>
      <%= @micropost.Watchers %>
      <% if current_user != nil %>
        <% if !Watcher.exists?(:micropost_id => @micropost.id, :user_id => current_user.id) %>
          <%= link_to 'Watch this issue', watch_url(id: @micropost.id, view: "micropost"), method: :post, class: "vote" %>
        <% else %>
          <%= link_to 'Stop watching', watch_url(id: @micropost.id, view: "micropost"), method: :post, class: "vote" %>
        <% end %>
      <% end %>
    </p>
</div>

<p>
  <% if @micropost.things.attached? %>
    <strong>Attachments:</strong>
    <% @micropost.things.each do |thing| %>
      <% if thing.previewable? %>
        <%= image_tag(thing.preview(resize: '200x200')) %>
      <% end %>
      <p>
        <a class="attachment_url" href=<%= url_for(thing)%> > <%=thing.filename%> </a>
        <% if 1 %>
          <%= link_to 'Remove', micropost_delete_attachment_url(thing.id),
                              method: :delete,
                              data: { confirm: 'Are you sure you want to delete this attachment?' } %>
        <% end %>
      </p>
    <% end %>
  <% end %>
</p>

<div class="issue_comments">
  <h3>Comments (<%= @micropost.comments.count %>)</h3>
  <p>
  <% @micropost.comments.each do |comment| %>
    <p>
    <strong><%=comment.user.name%></strong>
    <% if comment.user.id == @micropost.user_id %>
    Reporter
    <% end %>
    <p><%= comment.body %></p>
    </p>
    <% if logged_in? %>
      <% if comment.user.id == current_user.id %>
        <%= link_to 'Edit', edit_micropost_comment_path(@micropost, comment) %>
        <%= link_to 'Delete', [comment.micropost, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
      <% end %>
    <% end %>
    <%= time_ago_in_words(comment.created_at) + " ago" %>
    <% end %>
  <% if logged_in? %>
    <%= render 'comment_form', micropost: @micropost %>
  <% end %>
</div>